spring:
  profiles:
    active: dev
  datasource:
    username: admin
    password: cst323gcu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.asgardeo.io/t/jvdw/oauth2/token
          jwk-set-uri: https://api.asgardeo.io/t/jvdw/oauth2/jwks
logging:
  file:
    path: logs/
    name: logs/application.log
springdoc:
  default-produces-media-type: application/json
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://cst323activity.cz6nq4gs34ua.us-west-1.rds.amazonaws.com:3306/ARCHIVE_STAGE
logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://cst323activity.cz6nq4gs34ua.us-west-1.rds.amazonaws.com:3306/ARCHIVE
server:
  port: 80
