spring:
  datasource:
    url: jdbc:mysql://cst323activity.cz6nq4gs34ua.us-west-1.rds.amazonaws.com:3306/ARCHIVE_STAGE
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE