spring:
  datasource:
    url: jdbc:mysql://cst323activity.cz6nq4gs34ua.us-west-1.rds.amazonaws.com:3306/ARCHIVE
    username: admin
    password: cst323gcu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE